version: '3.8'
services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=80
      - NODE_ENV=production
    restart: always 